#!/bin/bash
#PBS -l mem=256gb,nodes=1:ppn=24,walltime=72:00:00
#PBS -m abe
#PBS -M konox006@umn.edu
#PBS -q mesabi

module load java
module load gatk

#	Path to the reference
REF=${HOME}/Shared/References/Reference_Sequences/Barley/Morex/Morex_Reference.fasta
#	Path to the capture design
CAP_DES=${HOME}/Shared/References/Reference_Sequences/Barley/Morex/Morex_Reference_ExCap_Design.bed
#	Path to directory containing GVCFs
GVCF_DIR=/panfs/roc/scratch/tkono/Genomic_Prediction/GVCFs
#	 Build the sample list
SAMPLE_LIST=($(find ${GVCF_DIR} -name '*.g.vcf'))
#	Put them into a format that will be accepted by the GATK command line
GATK_IN=()
for s in "${SAMPLE_LIST[@]}"
do
		GATK_IN+=("-V $s")
	done
#	Make sure the output directory exists
OUTPUT_DIR=/panfs/roc/scratch/tkono/Genomic_Prediction/Variants
mkdir -p ${OUTPUT_DIR}

#	GenotypeGVCFs options:
#		-R Reference
#		-L BED: Operate only over the intervals listed in BED
#		-V Input GVCF
#		-o Output VCF
#		--heterozygosity 0.008: Use a prior on nucleotide diversity of 0.008/bp
#		--sample_ploidy 1: treat samples as haploid (they are highly inbred)
#		-nct 24: use 24 CPU threads

export _JAVA_OPTIONS="-Xmx255g"
java -jar /panfs/roc/itascasoft/gatk/3.3.0/GenomeAnalysisTK.jar\
	-T GenotypeGVCFs \
	-R ${REF} \
	-L ${CAP_DES}\
	${GATK_IN[@]}\
	--heterozygosity 0.008\
	--sample_ploidy 1\
	-nt 24 \
	-o ${OUTPUT_DIR}/BadMutationsII_FirstPassVariants_20Par.vcf
