#   Script to plot a large grid of mapping quality distributions for a
#   directory of sample coverage values. They can be generated by running
#   `samtools view -S sample.bam | cut -f 5 | gzip -c > sample_coverage.txt.gz`

args <- commandArgs(TRUE)

#   List the files in the directory. They are gzipped text files.
coverage_files <- list.files(args[1], pattern="*.txt.gz", full.names=TRUE)

#   We are only interested in chromosomes 1H-7H
chromosomes <- c("chr1H", "chr2H", "chr3H", "chr4H", "chr5H", "chr6H", "chr7H")

#   Read them in and calculate the fold coverage over each feature. This is
#   a complicated data structure:
#   sample
#       chromosome
#           position
#           coverage
#   as nested lists.
coverage_values <- lapply(
    coverage_files,
    function(x) {
        v <- read.table(gzfile(x), header=F)
        #   Calculate the coverage values for each chromosome
        covdata <- lapply(
            chromosomes,
            function(y) {
                chrvals <- v[v$V1 == y,]
                x <- (chrvals$V2 + chrvals$V3)/2
                z <- (chrvals$V4 * 100)/(chrvals$V3 - chrvals$V2)
                return(list(pos=as.numeric(x), cov=as.numeric(z)))
            }
        )
        return(covdata)
    }
)

#   Also get the sample names
sample_names <- lapply(
    coverage_files,
    function(x) {
        fname <- basename(x)
        sname <- unlist(strsplit(fname, "_"))[1]
        return(sname)
    }
)

#   Plot them
lapply(
    seq_along(sample_names),
    function(x) {
        #   Calculate the mean coverage for the whole sample
        wgcov <- unlist(
            lapply(
                seq_along(chromosomes),
                function(w) {
                    return(coverage_values[[x]][[w]]$cov)
                    }
                )
            )
        pdf(file=paste(sample_names[[x]], "_WX_Coverage.pdf", sep=""), width=6, height=6)
        plot(
            density(log10(wgcov)),
            xlab="Log10 of Approximate Fold Coverage",
            ylab="Density",
            main="Coverage Distribution of Exome Capture Targets"
            )
        abline(v=log10(mean(wgcov)), lwd=2, col="red")
        dev.off()
        pdf(file=paste(sample_names[[x]], "_Coverage.pdf", sep=""), width=16, height=11)
        par(mfrow=c(4, 2))
        lapply(
            seq_along(chromosomes),
            function(y) {
                chrname <- chromosomes[y]
                plot(
                    x=coverage_values[[x]][[y]]$pos/1000000,
                    y=log10(coverage_values[[x]][[y]]$cov),
                    type="n",
                    ylab="Log10 of Approximate Fold Coverage",
                    xlab="Physical Position (Mb)",
                    xlim=c(0, 750),
                    xaxp=c(0, 750, 15),
                    main=chrname
                    )
                lines(
                    x=coverage_values[[x]][[y]]$pos/1000000,
                    y=log10(coverage_values[[x]][[y]]$cov),
                    col="black",
                    lwd=0.25
                    )
                abline(h=log10(mean(wgcov)), lwd=2, col="red")
            }
        )
        dev.off()
    }
)
