#   Script to plot a large grid of mapping quality distributions for a
#   directory of sample mapq values. They can be generated by running
#   `samtools view -S sample.bam | cut -f 5 | gzip -c > sample_mapq.txt.gz`

args <- commandArgs(TRUE)

#   List the files in the directory. They are gzipped text files.
mapq_files <- list.files(args[1], pattern="*.txt.gz", full.names=TRUE)

#   Read them in as vectors and convert to tables
mapq_values <- lapply(
    mapq_files,
    function(x) {
        v <- read.table(gzfile(x), header=F)$V1
        counts <- table(v)
        return(counts)
    }
)

#   Also get the sample names
sample_names <- lapply(
    mapq_files,
    function(x) {
        fname <- basename(mapq_files)
        sname <- unlist(strsplit(fname, "_"))[1]
        return(sname)
    }
)

#   Plot them
pdf(file="MAPQ_Plots.pdf", width=20, height=20)
par(mfrow=c(5, 4))
#   make the barplots
lapply(
    seq_along(mapq_values),
    function(x) {
        barplot(
            mapq_values[[x]]/1000000,
            xlab="Mapping Quality",
            ylab="Count (Millions of Reads)",
            main=sample_names[[x]],
            ylim=c(0, 30))
    }
)
dev.off()
